### ISSUE TITLE
Erreur Diverses

### ISSUE THREAD

**Issue by Purexo** [d-durand/mini-fwk#1]
Bonjour monsieur, j'ai fais l'exercice demandé (cad le formulaire d'inscription)  
Une fois le formulaire remplis conformément au consignes le site me renvois les erreur diverses ci dessous :  
C:\wamp\www\taf-iut\framework\lib\tpl\templates_c\b3d6fa1866c06972dbf9f6ef1375884a226f056b.file.index.tpl.php:32 Undefined index: form  
C:\wamp\www\taf-iut\framework\lib\tpl\templates_c\b3d6fa1866c06972dbf9f6ef1375884a226f056b.file.index.tpl.php:32 Trying to get property of non-object

Je vous joint ma classe et le template_cache qui bug  
[mon code](https://purexo.eu/zerobin/?daeda248db540e60#dxZUlIrsx1wRvTf086KEOLAYAj9Hil3vgsN20QwjULg=) - [le template_cache](https://purexo.eu/zerobin/?9151bb5c3677fd70#n76h2Kr/cBPNVGSgsIjYabx3IHUehrTMk3nx1W8t7k8=)

Sinon je souhaitais savoir ou créer des classes générales pour les utiliser dans n'importe quelle module.(par exemple une classe User) ?

Cordialement

**Comment by mbaumanndev** [comment]
En gros PHP n'arrive pas à accéder à l'index "form" du tableau de stockage des variables de smarty.
As-tu ton fichier tpl original sous la main ? Si il y'a une erreur elle vient surement de là.

**Comment by mbaumanndev** [comment]
Je fais un second message concernant les classes utilisables dans n'importe quel module :

Tu as deux solutions pour ça :
- Editer le fichier d'autoload pour ajouter le répertoire ou se situent tes classes
- Les ajoutées dans le dossier table, le dossier contient un objet membre et une classe pour le "lié" à la base de donnée

En espérant t'avoir apporté des éléments de réponse.

**Comment by Purexo** [comment]
Effectivement l'erreur venais bien du template, ça m'apprendra à copier coller des fichiers xD

Merci pour l'aide et ces indications, je me pencherai sur la création de classe dans un dossier perso.

**Comment by mbaumanndev** [comment]
De rien ^^

Pense à clôturer l'issue sur GitHub pour l'archiver, tu pourras la ré-ouvrir en cas de nouveaux problèmes.
